services:
  spring-api-image:
    image: superherogame-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_DB: ${POSTGRESDATABASE}
      POSTGRES_USER: ${POSTGRESUSERNAME}
    ports:
      - "5433:5432"
    networks:
      - spring-network
    volumes:
      - pg-data:/var/lib/postgresql/data
networks:
  spring-network:
volumes:
  pg-data: